version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    build: .
    command: /bin/server
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
  worker:
    build: .
    command: /bin/worker
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
